version: '3.9'

services:
  client:
    network_mode: host
    build: 
      context: .
      dockerfile: ./Dockerfile.client
    depends_on:
      - server
  server:
    network_mode: host
    build: 
      context: .
      dockerfile: ./Dockerfile.server